function SetThemeColours()
  --these will reset ANSI colours (alt-6, or game->configure->ansi colours)
  SetNormalColour (1,ColourNameToRGB("black"))
  SetNormalColour (2,ColourNameToRGB("crimson"))
  SetNormalColour (3,ColourNameToRGB("forestgreen"))
  SetNormalColour (4,ColourNameToRGB("chocolate"))
  SetNormalColour (5,ColourNameToRGB("dodgerblue"))
  SetNormalColour (6,ColourNameToRGB("magenta"))
  SetNormalColour (7,ColourNameToRGB("cadetblue"))
  SetNormalColour (8,ColourNameToRGB("lightgrey"))
  SetBoldColour (1,ColourNameToRGB("gray"))
  SetBoldColour (2,ColourNameToRGB("red"))
  SetBoldColour (3,ColourNameToRGB("chartreuse"))
  SetBoldColour (4,ColourNameToRGB("yellow"))
  SetBoldColour (5,ColourNameToRGB("mediumblue"))
  SetBoldColour (6,ColourNameToRGB("mediumvioletred"))
  SetBoldColour (7,ColourNameToRGB("teal"))
  SetBoldColour (8,ColourNameToRGB("white"))
end --function SetThemeColours

--colours extracted from mushclient under game -> configure -> ansi colours
black = RGBColourToName(GetNormalColour(1))
red = RGBColourToName(GetNormalColour(2))
green = RGBColourToName(GetNormalColour(3))
yellow = RGBColourToName(GetNormalColour(4))
blue = RGBColourToName(GetNormalColour(5))
magenta = RGBColourToName(GetNormalColour(6))
cyan = RGBColourToName(GetNormalColour(7))
white = RGBColourToName(GetNormalColour(8))
brightblack = RGBColourToName(GetBoldColour(1))
brightred = RGBColourToName(GetBoldColour(2))
brightgreen = RGBColourToName(GetBoldColour(3))
brightyellow = RGBColourToName(GetBoldColour(4))
brightblue = RGBColourToName(GetBoldColour(5))
brightmagenta = RGBColourToName(GetBoldColour(7))
brightcyan = RGBColourToName(GetBoldColour(7))
brightwhite = RGBColourToName(GetBoldColour(8))
foreground = white
background = black

BLACK = ColourNameToRGB (black)
RED = ColourNameToRGB (red)
GREEN = ColourNameToRGB (green)
YELLOW = ColourNameToRGB (yellow)
BLUE = ColourNameToRGB (blue)
MAGENTA = ColourNameToRGB (magenta)
CYAN = ColourNameToRGB (cyan)
WHITE = ColourNameToRGB (white)
BRIGHTBLACK = ColourNameToRGB (brightblack)
BRIGHTRED = ColourNameToRGB (brightred)
BRIGHTGREEN = ColourNameToRGB (brightgreen)
BRIGHTYELLOW = ColourNameToRGB (brightyellow)
BRIGHTBLUE = ColourNameToRGB (brightblue)
BRIGHTMAGENTA = ColourNameToRGB (brightmagenta)
BRIGHTCYAN = ColourNameToRGB (brightcyan)
BRIGHTWHITE = ColourNameToRGB (brightwhite)
FOREGROUND = BRIGHTWHITE
BACKGROUND = BRIGHTBLACK
