ImportXML
[[
<aliases
   muclient_version="4.90"
   world_file_version="15"
   date_saved="2017-03-05 19:00:00"
  >
  <alias
    name="my_alias"
    script="brutal_alias"
    match="#brutal*"
    enabled="y"
    group="brutal_plugin_aliases"
    send_to="13"
    sequence="100"
  >
  </alias>
</aliases>
]]
