ImportXML
[[
  <triggers
     muclient_version="4.90"
     world_file_version="15"
     date_saved="2017-03-05 19:00:00"
    >
    <trigger
      group="brutal_prompt_group"
      match="#brutal hp (?&lt;truehp&gt;(-\d+)|\d+)\:(?&lt;maxhp&gt;\d+)\:(?&lt;hp&gt;\d+) sp (?&lt;truesp&gt;(-\d+)|\d+)\:(?&lt;maxsp&gt;\d+)\:(?&lt;sp&gt;\d+) ep (?&lt;trueep&gt;(-\d+)|\d+)\:(?&lt;maxep&gt;\d+)\:(?&lt;ep&gt;\d+) xp (?&lt;xp&gt;(-\d+)|\d+)\:(?&lt;exptolvl&gt;(-\d+|\d+))\:(?&lt;protolvl&gt;(-\d+|\d+))\% ad (?&lt;exptoadv&gt;(-\d+|\d+))\:(?&lt;protoadv&gt;(-\d+|\d+))\% df (?&lt;df&gt;\d+) \$\$ (?&lt;cash&gt;\d+) ph (?&lt;phase&gt;\S+) dt (?&lt;dt&gt;\S+) hr (?&lt;hr&gt;.+) st(?&lt;st&gt;.+)\:$"
      name="prompt_trigger"
      sequence="100"
      send_to="14"
      script="capture_prompt"
      omit_from_output="y"
      regexp="y"
    >
    </trigger>
    <trigger
     enabled="y"
     group="brutal_prompt_group"
     keep_evaluating="y"
     match="^HP:\[(.+)\]\s+(?&lt;hp&gt;\d+)\%\s+SP:\[.+\]\s+(?&lt;sp&gt;\d+)\%\s+EP:\[.+\]\s+(?&lt;ep&gt;\d+)\%$"
     name="healthbar_trigger"
     omit_from_output="n"
     regexp="y"
     script="healthbar_update"
     sequence="100"
    >
    </trigger>
    <trigger
     enabled="y"
     group="brutal_prompt_group"
     keep_evaluating="y"
     match="^You feel fully healed\.$"
     regexp="y"
     script="fully_healed"
     sequence="100"
    >
    </trigger>
    <trigger
     enabled="y"
     group="brutal_prompt_group"
     keep_evaluating="y"
     match="^You feel fully rested\.$"
     regexp="y"
     script="fully_rested"
     sequence="100"
    >
    </trigger>
    <trigger
     enabled="y"
     group="brutal_prompt_group"
     keep_evaluating="y"
     match="^Your magical power has returned to full strength\.$"
     regexp="y"
     script="fully_magical"
     sequence="100"
    >
    </trigger>
    <trigger
     enabled="y"
     group="reset_status"
     keep_evaluating="y"
     match="^You are prepared to release the spell\.$"
     regexp="y"
     script="clear_prompt_status"
     sequence="100"
    >
    </trigger>
    <trigger
     enabled="y"
     group="reset_status"
     keep_evaluating="y"
     match="^You decide to try a combat maneuver\!\.$"
     regexp="y"
     script="clear_prompt_status"
     sequence="100"
    >
    </trigger>
    <trigger
     enabled="y"
     group="reset_status"
     keep_evaluating="y"
     match="^You are done building the camping place\.$"
     regexp="y"
     script="clear_prompt_status"
     sequence="100"
    >
    </trigger>
  </triggers>
]]
