require "global.variables"
require "global.usercfg"
require "global.functions"
require "global.help"
require "global.alias"
require "global.prompt"
require "global.infobar"
require "global.statuswin"
